kind: Service
apiVersion: v1
metadata:
  name: devchatdemo-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: devchatdemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: flask

