apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: devchatdemo
  namespace: default
  labels:
    app: devchatdemo
    deepsecurity-policy: PCI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devchatdemo
  template:
    metadata:
      labels:
        app: devchatdemo
    spec:
      containers:
        - image: 529505258873.dkr.ecr.us-east-1.amazonaws.com/devchatdemo
          name: devchatdemo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: flask

