kind: Service
apiVersion: v1
metadata:
  name: devchatdemo-service
  namespace: devchatdemo
spec:
  type: LoadBalancer
  selector:
    app: jeffsbooks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: flask

